apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
  labels:
    app: counter-job
spec:
  # Setting replicas to 1
  replicas: 5
  selector:
    matchLabels:
      app: counter-job
  template:
    metadata:
      labels:
        app: counter-job
    spec:
      containers:
      - name: counter-container
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Initialize counter
            i=1
            max={{ .Values.maxCount }}
            echo "Starting counter "

            # Loop until the condition is met
            while true; do

              # 1. Check exit condition first
              if [ $i -gt $max ]; then
                echo "Counter $i is greater than $max. Exiting with error (exit 1)."
                exit 1
              fi

              # 2. Log the current count
              echo "$(date) | Current count: $i"

              # 3. Increment and sleep
              i=$((i + 1))
              sleep 1
            done
        resources:
          limits:
            cpu: "10m"
            memory: "30Mi"